services:
  - type: web
    name: sportsvault-api
    runtime: node
    repo: https://github.com/Krishnass05/sportsvault
    branch: main
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DB_HOST
        value: db.ubzcciloddftlpvfukln.supabase.co
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: postgres
      - key: DB_SSL
        value: "true"
      - key: JWT_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: NMIMS Blr Sports Arena
      - key: EMAIL_FROM_ADDRESS
        value: no-reply@nmimsblrsportsarena.in